### ISSUE TITLE
This ingredient should have been flagged

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#9]
CERA ALBA/BEESWAX/CIRE DABEILLE, 

But because of the way it is written, it wasn't

**Comment by lmgardner** [comment]
Even with spaces it wasn't flagged ... should be flagged for beeswax

**Comment by josephgardner** [comment]
Was it supposed to just match bees wax?

https://github.com/josephgardner/isitcg/blob/master/ingredientrules.json#L88

Sent from my iPhone

On Apr 28, 2017, at 1:16 PM, lmgardner <notifications@github.com<mailto:notifications@github.com>> wrote:


CERA ALBA/BEESWAX/CIRE DABEILLE,

But because of the way it is written, it wasn't

**Comment by josephgardner** [comment]
Ok

**Comment by lmgardner** [comment]
Oh maybe

Sent from my iPhone

On Apr 28, 2017, at 2:11 PM, josephgardner <notifications@github.com<mailto:notifications@github.com>> wrote:

Was it supposed to just match bees wax?

https://github.com/josephgardner/isitcg/blob/master/ingredientrules.json#L88

Sent from my iPhone

On Apr 28, 2017, at 1:16 PM, lmgardner <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


CERA ALBA/BEESWAX/CIRE DABEILLE,

But because of the way it is written, it wasn't

**Comment by josephgardner** [comment]
Should I treat slashes as commas?

**Comment by josephgardner** [comment]
Can you verify this is fixed, and close ?

**Comment by josephgardner** [comment]
Fixed with #63
